### ISSUE TITLE
please remove the link to fpvis.org from settings

### ISSUE THREAD

**Issue by tlambert03** [FPvisualization/fpvisualization.github.io#7]
Hey @kthorn, could you remove the fpvis.org link from your settings on this page?

It appears to be a trash/scam site these days, and I got contacted at fpbase about the confusion.  I do credit this repo in my [license info](https://www.fpbase.org/privacy/) on fpbase, and the presence of that link to fpvis.org has confused/concerned the IT professional who reached out. 

thanks

**Comment by kthorn** [comment]
Deleted. Sorry about that!

**Comment by tlambert03** [comment]
Thanks!  Hope you are well :)
